# Shared packages installed on both Macs. Machine-specific extras belong in
# Brewfile.personal or Brewfile.work. Runtime versions belong to mise.
tap "infisical/get-cli"
tap "hashicorp/tap"

brew "dotbot"
brew "mise"
brew "starship"
brew "python"
brew "git"
brew "gh"
brew "glab"
brew "infisical/get-cli/infisical", trusted: true
brew "hashicorp/tap/vault", trusted: true
brew "fzf"
brew "zoxide"
brew "eza"
brew "bat"
brew "bottom"
brew "k9s"
brew "ripgrep"
brew "fd"
brew "git-delta"
brew "yq"
brew "atuin"
brew "opencode"

brew "cloudflare-speed-cli"
brew "speedtest-go"

cask "font-symbols-only-nerd-font"
cask "ghostty"
cask "visual-studio-code"
cask "spotify"
cask "discord"
cask "1password-cli"
cask "docker-desktop"
cask "herd"
cask "raycast"
cask "tablepro"
cask "tinkerwell"
cask "tailscale-app"
cask "homebrew-app"
cask "beyond-compare"
cask "claude-code"
cask "codex"
cask "gitkraken"
cask "headlamp"
cask "jetbrains-toolbox"
cask "lens"
cask "obsidian"
cask "opencode-desktop"
