search_mode = "daemon-fuzzy"
workspaces = true
style = "auto"
enter_accept = true
auto_sync = true

[ai]
enabled = true

[daemon]
enabled = true
autostart = true

[theme]
name = "catppuccin-mocha-mauve"
